---
title: "Events per Person in Joint Competing Model"
author: "Lacey Etzkorn"
date: "11/23/2020"
output: html_document
---

# Vary Parameters (Theta, BetaR)

```{r, message = FALSE, warning = FALSE, echo = FALSE, fig.height = 8, fig.width = 12}
library(frailtypack); library(tidyverse)
source("../delirium_package/R/simulate_joint_data.R")
source("../delirium_package/R/random_weibull.R")
source("../delirium_package/R/extract_frailtypack_coef_weibullgap.R")
set.seed(111720)
par0 = list(
       c(betaR = 1, etaR = .5,
         betaD = 1, etaD = 1,
         theta = 1, alpha1 = 0.1,
         trtR = 0.5, trtD = 0),
      c(betaR = 1, etaR = .5,
         betaD = 1, etaD = 1,
         theta = 0.5, alpha1 = 0.1,
         trtR = 0.5, trtD = 0),
       c(betaR = 1, etaR = .5,
         betaD = 1, etaD = 1,
         theta = 1, alpha1 = 1,
         trtR = 0.5, trtD = 0),
      c(betaR = 1, etaR = .5,
         betaD = 1, etaD = 1,
         theta = 0.5, alpha1 = 1,
         trtR = 0.5, trtD = 0)
       )
data0 <- 
map(par0, 
    ~simulate.joint.data(n = 10000,truncate = 2,par0 = .))

```

# Survival Times
```{r}
tibble(data0 = data0,
       par = c("Theta = 1, Alpha = 0.1", 
       	      "Theta = 0.5, Alpha = 0.1",
       	      "Theta = 1, Alpha = 1",
       	      "Theta = 0.5, Alpha = 1")) %>%
mutate(events = 
  map(data0,
    ~group_by(., id) %>% 
     summarise(t = max(t)) %>%
     ungroup))%>%
unnest(events) %>% 
ggplot()+
geom_freqpoly(aes(x = t, color = par))+ 
ggtitle("Total Observation Time")
```

# Event Counts

```{r}
tibble(data0 = data0,
       par = c("Theta = 1, Alpha = 0.1", 
       	      "Theta = 0.5, Alpha = 0.1",
       	      "Theta = 1, Alpha = 1",
       	      "Theta = 0.5, Alpha = 1")) %>%
mutate(events = 
  map(data0,
    ~group_by(., id) %>% 
     summarise(n.events = n()-1) %>%
     ungroup))%>%
unnest(events) %>% 
group_by(n.events, par) %>%
summarise(freq = n()/10000) %>%
group_by(par) %>%
mutate(mean.events = sum(n.events * freq)) %>% 
ggplot()+
geom_line(aes(x = n.events, y = freq))+ 
geom_vline(aes(xintercept = mean.events), color = "blue")+ 
facet_wrap("par") +
geom_text(aes(x = mean.events + 10, y = 0.1, label = round(mean.events,1))) +
ggtitle("Events per Person, Distribution and Average (blue)")
```
