---
title: "Check Data Generating Function"
author: "Lacey Etzkorn"
date: "1/23/2022"
output: html_document
---

```{r setup, include=FALSE}
load("../simulation_results/metaData.rdata")
knitr::opts_chunk$set(echo = TRUE)
library(frailtypack); library(tidyverse)
source("../delirium_package/R/joint_simulate_data.R")
source("../delirium_package/R/competing_simulate_data.R")
source("../delirium_package/R/random_weibull.R")
results <- tibble()
```


```{r}
meta1 <- filter(meta, sigma == .75, alpha1 == 0.5, alpha2 == 0,
         trtR == -0.25, trtD == -0.25, trtD2 == 0) %>%
	filter(simid==min(simid))
data0 <- simulate.competing.data(
	n = 10000,truncate = 28,
	par0 = unlist(dplyr::select(meta1, betaR:trtD2))) 

data0 %>%
	group_by(id) %>%
	summarise(
	         w = w[1],
	         event = sum(event),
	         trt = mean(trt),
	         terminal1 = sum(terminal1),
	         terminal2 = sum(terminal2),
	         t = max(t)) %>%
	ungroup %>%
	group_by(terminal1, terminal2, trt) %>%
	summarise(n = n(),
	          st = sum(t),
	          terminalPct = 100*n/sum(n),
	          .groups = "drop",
	          anyevent = sum(event>0),
	       event = sum(event),
	       eventsPer100Day = 100*event / st) %>%
	ungroup %>%
	group_by(trt) %>% 
	mutate(anyevent.trt = 100*sum(anyevent)/sum(n),
	       eventsPer100Day.trt = 100*sum(event) / sum(st)) %>%
	arrange(trt, desc(n))
```
### Effect on Death

```{r}
meta1 <- filter(meta, sigma == .75, alpha1 == 0.5, alpha2 == -0.5,
         trtR == -0.25, trtD == -0.25, trtD2 == -0.25) %>%
	filter(simid==min(simid))
data1 <- simulate.competing.data(
	n = 10000,truncate = 28,
	par0 = unlist(dplyr::select(meta1, betaR:trtD2))) 

data1 %>%
	group_by(id) %>%
	summarise(
	         w = w[1],
	         event = sum(event),
	         trt = mean(trt),
	         terminal1 = sum(terminal1),
	         terminal2 = sum(terminal2),
	         t = max(t)) %>%
	ungroup %>%
	group_by(terminal1, terminal2, trt) %>%
	summarise(n = n(),
	          st = sum(t),
	          terminalPct = 100*n/sum(n),
	          .groups = "drop",
	          anyevent = sum(event>0),
	       event = sum(event),
	       eventsPer100Day = 100*event / st) %>%
	ungroup %>%
	group_by(trt) %>% 
	mutate(anyevent.trt = 100*sum(anyevent)/sum(n),
	       eventsPer100Day.trt = 100*sum(event) / sum(st)) %>%
	arrange(trt, desc(n))
```

# Make Delirium Prevalence the Same

```{r}
data0 <- simulate.competing.data(
	n = 10000,truncate = 28,
	par0 = c(betaR = 0.35, etaR = 6.64,
	         betaD = 2.59, etaD = 78.5,
	         betaD2 = .5, etaD2 = 8.23, 
	         sigma = 0.25, 
	         alpha1 = 14.8, alpha2 = -6,
	         trtR = -0.25, trtD = -0.25, trtD2 = -0.5)) 

data0 %>%
	group_by(id) %>%
	summarise(
	         w = w[1],
	         event = sum(event),
	         trt = mean(trt),
	         terminal1 = sum(terminal1),
	         terminal2 = sum(terminal2),
	         t = max(t)) %>%
	ungroup %>%
	group_by(terminal1, terminal2, trt) %>%
	summarise(n = n(),
	          st = sum(t),
	          terminalPct = 100*n/sum(n),
	          .groups = "drop",
	          anyevent = sum(event>0),
	       event = sum(event),
	       eventsPer100Day = 100*event / st) %>%
	ungroup %>%
	group_by(trt) %>% 
	mutate(anyevent.trt = 100*sum(anyevent)/sum(n),
	       eventsPer100Day.trt = 100*sum(event) / sum(st)) %>%
	arrange(trt, desc(n))
```

# Make Incidence the Same

```{r}
data0 <- simulate.competing.data(
	n = 10000,truncate = 28,
	par0 = c(betaR = 0.35, etaR = 6.64,
	         betaD = 2.59, etaD = 78.5,
	         betaD2 = .5, etaD2 = 8.23, 
	         sigma = 0.25, 
	         alpha1 = 14.8, alpha2 = -12,
	         trtR = -0.25, trtD = -0.25, trtD2 = 2)) 

data0 %>%
	group_by(id) %>%
	summarise(
	         w = w[1],
	         event = sum(event),
	         trt = mean(trt),
	         terminal1 = sum(terminal1),
	         terminal2 = sum(terminal2),
	         t = max(t)) %>%
	ungroup %>%
	group_by(terminal1, terminal2, trt) %>%
	summarise(n = n(),
	          st = sum(t),
	          terminalPct = 100*n/sum(n),
	          .groups = "drop",
	          anyevent = sum(event>0),
	       event = sum(event),
	       eventsPer100Day = 100*event / st) %>%
	ungroup %>%
	group_by(trt) %>% 
	mutate(anyevent.trt = 100*sum(anyevent)/sum(n),
	       eventsPer100Day.trt = 100*sum(event) / sum(st)) %>%
	arrange(trt, desc(n))
```

# Make Both the Same?

```{r}
results <- tibble()
meta <-     expand.grid(betaR = 0.5, etaR = 66,
		betaD = 1.6, etaD = 25.2,
		betaD2 = 1.3, etaD2 = 7.7,
		sigma = 0.25,
		alpha1 = 2,
		alpha2 =  seq(-2,2, by=0.25),
		trtR = -0.25,
		trtD = -0.25,
		trtD2 = seq(-1,1, by=0.1))

for(i in 1:nrow(meta)){
data0 <- simulate.competing.data(
	n = 1000,truncate = 28,
	par0 = unlist(meta[i,])) 
results <- data0 %>%
	group_by(id) %>%
	summarise(
	         w = w[1],
	         event = sum(event),
	         trt = mean(trt),
	         terminal1 = sum(terminal1),
	         terminal2 = sum(terminal2),
	         t = max(t)) %>%
	ungroup %>%
	group_by(trt) %>% 
	summarise(anyevent = 100*mean(event>0),
	       eventsPer100Day = 100*mean(event)) %>%
	ungroup %>%
	bind_rows(results)
}



results$i<- rep(1:nrow(meta),each = 2)

results2 <- results %>% group_by(i) %>%
	summarise(anyDiff = anyevent[2]-anyevent[1],
	       dayDiff = eventsPer100Day[2] - eventsPer100Day[1],
	       weird = anyDiff>0 & dayDiff>0) %>%
	bind_cols(meta)
ggplot(results2) +
geom_raster(aes(x = alpha2, y = trtD2, fill = weird))

filter(results2, anyDiff > 0, dayDiff > 0) %>%
ggplot()+geom_histogram(aes(x = i))

```
