---
title: "Examples of Univariate and Multivariate Terminal Events in Joint Model"
author: "Lacey Etzkorn"
date: "8/31/2020"
output: html_document
---

```{r setup, include=FALSE}
rm(list = ls())
knitr::opts_chunk$set(echo = FALSE)
library(frailtypack); library(tidyverse)
data(dataMultiv)
data(readmission)
data(dataNCC)

#Process Readmission Data
#ids <- sample(unique(readmission$id),size = 200, replace = F)
readmission <- readmission %>% 
	mutate(discharge = 0)#%>%
 	#filter(id %in% ids)
readmission <- readmission %>%
	mutate(id = id + max(id),
	       discharge = death, 
	       death = 0) %>% 
	bind_rows(readmission)%>%
	mutate(sex = as.numeric(sex) - 1,
	       id = dense_rank(id)) %>%
	arrange(id, t.stop)
```

# Weibull Gap Models

### Readmission Data, Classic Joint Model

```{r, fig.height = 10, fig.width=12}
file.remove("joint_model_parameters.dat")
joint.readmission <- 
frailtyPenal(
Surv(time,event)~cluster(id)+sex+terminal(death),
formula.terminalEvent=~sex,
data=readmission,
hazard = "Weibull",
recurrentAG=FALSE)

par <- read_file(file = "joint_model_parameters.dat") %>%
	strsplit("\\s+") %>% unlist %>% as.numeric
df <- as.numeric(par)[-1] %>%
	matrix(ncol = 9, byrow = T) %>%
	as.data.frame

colnames(df) <- c("LL", "betaR.5", "etaR.5", "betaD.5", "etaD.5",
	      "theta.5", "alpha1", "trtR", "trtD")
df <-
	df %>%
	as_tibble %>%
	mutate(n = 1:n()) %>%
	gather("par","val",-n)

df %>% 
filter( n < 1000, n >= 0) %>%
ggplot() +
geom_line(aes(x = n, y = val)) +
geom_point(aes(x = n, y = val)) +
facet_wrap("par", scales = "free_y") +
theme_bw(30) 
joint.readmission
```

## Readmission Data, Multivariate Model

```{r, fig.height = 14, fig.width=18}
if(file.exists("multiv_model_progress.dat")) file.remove("multiv_model_progress.dat")
if(file.exists("multiv_model_parameters.dat")) file.remove("multiv_model_parameters.dat")
if(file.exists("readmission_multiv_model_parameters.dat")) file.remove("readmission_multiv_model_parameters.dat")
multiv.readmission <- 
multivPenal(
formula = Surv(t.start, t.stop,event)~cluster(id)+sex+terminal(death)+terminal2(discharge),
formula.terminalEvent=~sex,
formula.terminalEvent2=~sex,
data=readmission,
hazard = "Weibull",
recurrentAG=F,
maxit = 200)

file.rename(from = "multiv_model_progress.dat", 
	 to =  "readmission_multiv_model_progress.dat")	
multiv.readmission$critCV
file.rename(from = "multiv_model_parameters.dat", 
	 to =  "readmission_multiv_model_parameters.dat")	
multiv.readmission$critCV

par <- read_file(file = "readmission_multiv_model_parameters.dat") %>%
	strsplit("\\s+") %>% unlist %>% as.numeric
df <- as.numeric(par)[-1] %>%
	matrix(ncol = 14, byrow = T) %>%
	as.data.frame

colnames(df) <- c("n","LL", "betaR.5", "etaR.5", "betaD.5", "etaD.5",
	      "betaD2.5", "etaD2.5", "theta.5",
	      "alpha1", "alpha2",
	      "trtR", "trtD", "trtD2")
df <- df %>% as_tibble %>% gather("par","val",-n)

df %>% #dplyr::filter(n > 400, n < 1200) %>%
ggplot() +
geom_line(aes(x = n, y = val)) +
geom_point(aes(x = n, y = val)) +
facet_wrap("par", scales = "free_y") +
theme_bw(30) 
```

## NCC Data, Univariate Model

```{r, fig.height = 10, fig.width=12, fig.width=9}
file.remove("joint_model_parameters.dat")
joint.ncc <- 
frailtyPenal(
Surv(gaptime,event)~cluster(id)+cov1+terminal(death),
formula.terminalEvent=~cov1,
data=dataNCC,
hazard = "Weibull",
recurrentAG=FALSE)

par <- read_file(file = "joint_model_parameters.dat") %>%
	strsplit("\\s+") %>% unlist %>% as.numeric
df <- as.numeric(par)[-1] %>%
	matrix(ncol = 9, byrow = T) %>%
	as.data.frame

colnames(df) <- c("LL", "betaR.5", "etaR.5", "betaD.5", "etaD.5",
	      "theta.5", "alpha1", "trtR", "trtD")
df <-
	df %>%
	as_tibble %>%
	mutate(n = 1:n()) %>%
	gather("par","val",-n)

df %>% 
#filter( n < 1000, n > 500) %>%
ggplot() +
geom_line(aes(x = n, y = val)) +
geom_point(aes(x = n, y = val)) +
facet_wrap("par", scales = "free_y") +
theme_bw(30)
```

## NCC Data, Multivariate Model

```{r, fig.height = 10, fig.width=12, eval = FALSE}
file.remove("frailty_model_parameters.dat")
data(dataNCC)
dataNCC <- dataNCC %>% mutate(discharge = 0)
dataNCC <- dataNCC %>%
	mutate(id = id + max(id),
	       discharge = death, 
	       death = 0) %>% 
	bind_rows(dataNCC)

multiv.ncc <- 
multivPenal(
formula = Surv(t.start, t.stop,event)~cluster(id)+cov1+terminal(death)+terminal2(discharge),
formula.terminalEvent=~cov1,
formula.terminalEvent2=~cov1,
data=dataNCC,
hazard = "Weibull",
recurrentAG=FALSE,
maxit = 350)

par <- read_file(file = "frailty_model_parameters.dat") %>%
	strsplit("\\s+") %>% unlist %>% as.numeric
df <- as.numeric(par)[-1] %>%
	matrix(ncol = 13, byrow = T) %>%
	as.data.frame

colnames(df) <- c("LL", "betaR.5", "etaR.5", "betaD.5", "etaD.5",
	      "betaD2.5", "etaD2.5", "theta.5",
	      "alpha1", "alpha2",
	      "trtR", "trtD", "trtD2")
df <-
	df %>%
	as_tibble %>%
	mutate(n = 1:n()) %>%
	gather("par","val",-n)

df %>% 
filter( n < 4000) %>%
ggplot() +
	geom_line(aes(x = n, y = val)) +
	facet_wrap("par", scales = "free_y") +
	theme_bw(30) 
```

## Tumor Data, Univariate Model

```{r tumoruni, fig.height = 10, fig.width=12}
 data <- dataMultiv
 colnames(data) <- tolower(colnames(data))
ids <- sample(unique(data$patient),size = 200, replace = F)
 data <- data %>%
 	filter(patient %in% ids,
 	       indicmeta != 1) %>%
 	group_by(patient) %>%
 	mutate(time0 = c(0,time1[-n()]),
 	       timegap = time1 - time0,
 	       discharge = 1-indicdeath-indicrec) %>%
 	dplyr::select(-indicmeta, -obs) %>%
 	ungroup()
 
file.remove("joint_model_parameters.dat")
joint.tumor<- frailtyPenal(Surv(time0, time1,indicrec) ~ v1 + cluster(patient) + terminal(indicdeath),
	          formula.terminalEvent =  ~ v1,
	          data = data,
	          recurrentAG=F,
	          hazard="Weibull")
par <- read_file(file = "joint_model_parameters.dat") %>%
	strsplit("\\s+") %>% unlist %>% as.numeric
df <- as.numeric(par)[-1] %>%
	matrix(ncol = 9, byrow = T) %>%
	as.data.frame

colnames(df) <- c("LL", "betaR.5", "etaR.5", "betaD.5", "etaD.5",
	      "theta.5", "alpha1", "trtR", "trtD")
df <-
	df %>%
	as_tibble %>%
	mutate(n = 1:n()) %>%
	gather("par","val",-n)

df %>% 
#filter( n < 900, n > 700) %>%
ggplot() +
geom_line(aes(x = n, y = val)) +
geom_point(aes(x = n, y = val)) +
facet_wrap("par", scales = "free_y") +
theme_bw(30)
```

## Tumor Recurrence Data, Multivariate Model

```{r tumormulti, fig.height=14, fig.width=18}
data <- data %>% mutate(discharge = 0)
data <- data %>%
	mutate(patient = patient + max(patient),
	       discharge = indicdeath, 
	       indicdeath = 0) %>% 
	bind_rows(data) %>%
	mutate(patient = dense_rank(patient)) %>%
	arrange(patient, time1)

if(!file.exists("recurrence_multiv_model_parameters.dat")){
if(file.exists("frailty_model_parameters.dat"))file.remove("frailty_model_parameters.dat")
multiv0<- multivPenal(Surv(time0, time1,indicrec) ~ v1 + cluster(patient) + terminal(indicdeath)+ terminal2(discharge),
	          formula.terminalEvent =  ~ v1,
	          formula.terminalEvent2 =  ~ v1,
	          data = data,
	          recurrentAG=F,
	          hazard="Weibull",
	          maxit = 1000)
file.rename(from = "frailty_model_parameters.dat", 
	 to =  "recurrence_multiv_model_parameters.dat")
}
par <- read_file(file = "recurrence_multiv_model_parameters.dat") %>%
	strsplit("\\s+") %>% unlist %>% as.numeric
df <- as.numeric(par)[-1] %>%
	matrix(ncol = 14, byrow = T) %>%
	as.data.frame

colnames(df) <- c("n","LL", "betaR.5", "etaR.5", "betaD.5", "etaD.5",
	      "betaD2.5", "etaD2.5", "theta.5",
	      "alpha1", "alpha2",
	      "trtR", "trtD", "trtD2")
df <-
	df %>%
	as_tibble %>%
	mutate(n = 1:n()) %>%
	gather("par","val",-n)

df %>% 
filter(n < 50) %>%
ggplot() +
geom_line(aes(x = n, y = val)) +
geom_point(aes(x = n, y = val)) +
facet_wrap("par", scales = "free_y") +
theme_bw(30) 
```

### Examine the Tail of the Trajectory More Closely

```{r, echo = FALSE, fig.height=14, fig.width=18}
df %>% 
filter(n > 20) %>%
ggplot() +
geom_line(aes(x = n, y = val)) +
geom_point(aes(x = n, y = val)) +
facet_wrap("par", scales = "free_y") +
theme_bw(30) 
```

## Try Jumping the Parameter

```{r tumormulti, fig.height=14, fig.width=18}
if(!file.exists("recurrence_multiv_model_parameters2.dat")){
if(file.exists("frailty_model_parameters.dat"))file.remove("frailty_model_parameters.dat")
multiv0 <- multivPenal(Surv(time0, time1,indicrec) ~ v1 + cluster(patient) + terminal(indicdeath)+ terminal2(discharge),
	          formula.terminalEvent =  ~ v1,
	          formula.terminalEvent2 =  ~ v1,
	          data = data,
	          recurrentAG=F,
	          hazard="Weibull",
	          maxit = 1000)
file.rename(from = "frailty_model_parameters.dat", 
	 to =  "recurrence_multiv_model_parameters2.dat")
}
par <- read_file(file = "recurrence_multiv_model_parameters.dat") %>%
	strsplit("\\s+") %>% unlist %>% as.numeric
df <- as.numeric(par)[-1] %>%
	matrix(ncol = 14, byrow = T) %>%
	as.data.frame

colnames(df) <- c("n","LL", "betaR.5", "etaR.5", "betaD.5", "etaD.5",
	      "betaD2.5", "etaD2.5", "theta.5",
	      "alpha1", "alpha2",
	      "trtR", "trtD", "trtD2")
df <-
	df %>%
	as_tibble %>%
	mutate(n = 1:n()) %>%
	gather("par","val",-n)

df %>% 
filter(n > 50) %>%
ggplot() +
geom_line(aes(x = n, y = val)) +
geom_point(aes(x = n, y = val)) +
facet_wrap("par", scales = "free_y") +
theme_bw(30) 
```

