---
title: "Simulation of Competing (Gap) Joint Model"
output: html_document
---
```{r setup, warning = FALSE, message = FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
library(frailtypack); library(tidyverse); library(gt)
source("../delirium_package/R/competing_simulate_data.R")
source("../delirium_package/R/random_weibull.R")
save.date <- "20211213"
set.seed(121321)
```

# Competing Joint Model

$$
    r_{ij}(t|w_i, X_{ij}) = r_0(t) \exp(X_{i} \gamma_r + \frac 12 [w_i + u_i]) \\
    \lambda_{i}^{(1)}(t|w_i, X_{ij}) = \lambda_0^{(1)}(t) \exp(X_{i} \gamma_1 + \alpha_{1} w_i) \\
    \lambda_{i}^{(2)}(t|w_i, X_{ij}) = \lambda_0^{(2)}(t) \exp(X_{i} \gamma_2 + \alpha_{2} u_i) \\
        r_0(t) =  \frac{\eta_r \cdot t^{\eta_r-1}}{\beta_r^{\eta_r}} \text{(weibull hazard)}\\
    \lambda_0^{(1)}(t) = \frac{\beta_1 \cdot t^{\beta_1-1}}{\eta_1^{\beta_1}} \text{(weibull hazard)}\\
    \lambda_0^{(2)}(t) = \frac{\beta_2 \cdot t^{\beta_2-1}}{\eta_2^{\beta_2}} \text{(weibull hazard)}\\
    w_i \sim_{IID} N(0,\sigma^2)
$$
# Simulation Values

```{r, fig.height = 14, fig.width=18}
par00 = c(betaR = 1, etaR = 10,
         betaD = 1.85, etaD = 25,      
         betaD2 = 1.15, etaD2 = 10,
         theta = 0.2, alpha1 = -0.12, alpha2 = -0.32,
         trtR = -0.08, trtD = 0.07, trtD2 = 0.08)
print(par00)
```

# Simulate One Data Set

```{r, fig.height = 14, fig.width=18}
data <- 
simulate.competing.data(n = 1500, truncate = 28, par0 = par00)

data %>% 
group_by(id) %>% 
summarise(del = any(event==1),
          no.del = sum(event==1),
          death = any(terminal1==1), 
          discharge = any(terminal2==1)) %>% 
summarise(`Delirium Prevalence` = mean(del), 
          `Max No. Delirium Events` = max(no.del), 
          `Proportion Died` = mean(death), 
          `Proportion Discharged` = mean(discharge), 
          `Delirium Prevalence among Mortalities` = mean(death*del)/mean(death), 
          `Delirium Prevalence among Discharges` = mean((discharge*del))/mean(discharge)) %>% 
t
```

# Fit One Competing Model

```{r}
mod0 <- 
multivPenal(
formula = Surv(t0, t, event)~cluster(id)+trt+terminal(terminal1)+terminal2(terminal2),
formula.terminalEvent=~trt,
formula.terminalEvent2=~trt,
data=data, 
jointGeneral = F,
initialize = T, 
save.progress = T,
hazard = "Weibull",
gapTimes=T,
maxit = 350)

mod0$summary.table
```

# Simulate Many Data Sets and Fit Competing Models

```{r, message = FALSE, warning = FALSE, echo = FALSE, fig.height = 8, fig.width = 12}
nsim = 10
par0 = rep(each = nsim, list(par00))

####################################################################
# Generate Data
if(!file.exists(paste0("../package_test_output/CompetingJointModels_",save.date,".rdata"))){
	data0 <- 
	map(par0, 
	    ~simulate.competing.data(n = 1200,truncate = 2,par0 = .))
	mod.joint <- list()
	# Fit models
	for(i in 1:length(par0)){
		mod.joint[[i]] <-
		multivPenal(formula = Surv(t0, t, event) ~ trt + cluster(id) +
				terminal(terminal1) + terminal2(terminal2),
			formula.terminalEvent = ~trt, 
			formula.terminalEvent2= ~trt,
			jointGeneral = F,
			save.progress = T,
			data = data0[[i]],
			gapTimes=T,
			hazard = "Weibull",
			maxit = 100, 
			initialize = T)
		cat("Model ", i, "complete.\n")
		save(data0, mod.joint, 
		     file = paste0("../package_test_output/CompetingJointModels_",save.date,".rdata"))
	}
} else load(file = paste0("../package_test_output/CompetingJointModels_",save.date,".rdata"))
```

# Verify Competing Joint Model Estimates

```{r, fig.height = 8, fig.width = 12}
truth =
tibble(Parameter = mod.joint[[1]]$summary.table$Parameter,
       truth = par00)

results <- 
tibble(data = 1:(nsim),
       est = map(mod.joint, ~.$summary.table),
       error = map(mod.joint, ~.$critCV[2]) %>% unlist %>% 
           factor(labels = c("None","Maxit","Calculation"),levels = c(1,2,4)),
       anyerror = map(mod.joint, ~.$critCV[2]!=1)%>% unlist,
       error2 = map(mod.joint, ~.$critCV[2] ==2) %>% unlist,
       error4 = map(mod.joint, ~.$critCV[2] ==4) %>% unlist) %>% 
unnest(c(est))

# Plot Results
results %>% 
ggplot()+
geom_point(aes(y = data, x = Estimate, color = error)) +
facet_wrap("Parameter", scales = "free") +
geom_vline(data = truth, aes(xintercept = truth), color = "red") +
scale_color_manual(values = c("black", "green", "red"))+
theme_bw()+
labs(title = paste0("Competing Joint Model Simulation Results(R =",length(par00),", n = ", length(unique(data0[[1]]$id)),")"))
```

```{r}
truth =
tibble(Parameter = mod.joint[[1]]$summary.table$Parameter,
       truth = par00)

results2 <- 
tibble(data = 1:(nsim),
       par1 = map(mod.joint, ~.$initialization$summary.table1$Parameter),
       est1 = map(mod.joint, ~.$initialization$summary.table1$Estimate),
       par2 = map(mod.joint, ~.$initialization$summary.table2$Parameter),
       est2 = map(mod.joint, ~.$initialization$summary.table2$Estimate)) %>% 
unnest(c(par1, est1, par2, est2))

# Plot Results
results2 %>%
filter(par1 %in% c("Shape, Recurrent","Scale, Recurrent", "Sigma", "Recurrent: trt")) %>%
ggplot()+
geom_point(aes(y = data, x = est1)) +
geom_point(aes(y = data, x = est2), color="blue", shape = 1) +
facet_wrap("par1", scales = "free") +
geom_vline(data = tibble(truth = par00[c("betaR","etaR","theta","trtR")],
		 par1 = c("Shape, Recurrent","Scale, Recurrent", 
		          "Sigma", "Recurrent: trt")),
           aes(xintercept = truth), color = "red") +
theme_bw()+
labs(title = paste0("Competing Joint Model Simulation Results(R =",length(par00),", n = ", length(unique(data0[[1]]$id)),")"))
```


```{r}
results %>% 
    filter(grepl("Alpha", Parameter)) %>%
    dplyr::select(data, Parameter, Raw) %>%
    pivot_wider(id_cols = data, names_from = "Parameter", values_from = "Raw") %>%
ggplot()+
    geom_point(aes(x = `Alpha, Terminal1`, y = `Alpha, Terminal2`))
```


```{r, echo = FALSE, message = FALSE, warning = FALSE}
tab_start <-
results %>%mutate(Truth = rep(truth$truth,nsim)) %>%
group_by(Parameter) %>%
summarise(Truth = Truth[1], 
          Mean = mean(Estimate[!anyerror], trim = 0.005),
          SD = mean((Estimate[!anyerror]-Mean)^2, na.rm=T, trim = 0.005)^.5,
          Est.SD = mean(Estimate.SE[!anyerror], na.rm=T, trim = 0.005), .groups = "drop"
) %>%
pivot_longer(cols = Mean:Est.SD) %>%
mutate(value = round(value, 3)) %>%
pivot_wider(names_from = c(name), values_from = value)

gt(tab_start, rowname_col = "Parameter")%>%
tab_stubhead(label = "Parameter")%>%
tab_header(
    title = md(paste0("Competing Joint Model Simulation Results(R =",length(par00),", n = ", length(unique(data0[[1]]$id)),")")))%>%
cols_label(
    Truth = html("True Value"),
    Mean = html("Avg. Estimate"),
    SD = html("SE"),
    Est.SD = html("Avg. Est. SE")
)
```

## Errors

```{r}
mean(results$anyerror)
mean(results$error2)
mean(results$error4)
```

# Comparison with Joint Model

```{r, echo = FALSE, message = FALSE, warning = FALSE}
truth =
tibble(Parameter = mod.joint[[1]]$summary.table$Parameter,
       truth = par00)

results2 <- 
tibble(data = rep(1:(nsim), 2), model = rep(1:2, each = nsim),
       Parameter = c(map(mod.joint, ~.$initialization$summary.table1$Parameter),
       	  map(mod.joint, ~.$initialization$summary.table2$Parameter)),
       Estimate = c(map(mod.joint, ~.$initialization$summary.table1$Estimate),
       	 map(mod.joint, ~.$initialization$summary.table2$Estimate)),
       Error = c(map(mod.joint, ~.$initialization$joint1$istop),
       	 map(mod.joint, ~.$initialization$joint1$istop))) %>% 
unnest(c(Parameter, Estimate, Error)) %>%
mutate(Truth = c(rep(par00[c(1:4,7:8,10:11)], nsim), rep(par00[c(1:2,5:7,9:10,12)], nsim)), 
       Error = Error!=1) %>%
group_by(model, Parameter)  %>%
summarise(Truth = Truth[1], 
          Mean = mean(Estimate[!Error]),
          SD = mean((Estimate[!Error]-Mean)^2, na.rm=T)^.5, .groups = "drop"
) %>%
pivot_wider(id_cols = Parameter, values_from = c(Truth, Mean, SD), names_from = model)

tab_start %>%
left_join(results2, by = "Parameter") %>%
select(Parameter, Truth, Mean, SD, Mean_1, SD_1, Mean_2, SD_2) %>%
gt(rowname_col = "Parameter")%>%
tab_stubhead(label = "Parameter")%>%
tab_header(
    title = md(paste0("**Competing Joint Model Simulation Results(R =",length(par00),", n = ", length(unique(data0[[1]]$id)),")**")))%>%
cols_label(
    Mean = html("Competing Estimate"),
    Mean_1 = html("Death Estimate"),
    Mean_2 = html("Discharge Estimate"),
    SD = html("SE"),
    SD_1 = html("SE"),
    SD_2 = html("SE")
) %>% 
fmt_number(c(4,6,8),pattern = "({x})")%>% 
fmt_number(c(3,5,7)) %>% 
fmt_missing(columns = 1:8, missing_text = "") %>%
cols_align(columns = c(4,6,8), align = c("left"))
```

